### ISSUE TITLE
Editable mode number only displaying 2 digits

### ISSUE THREAD

**Issue by goatandsheep** [PolymerElements/paper-slider#200]
### Description

When maximum is greater than 100 and `immediateValue` is above 100, the paper-input in editable mode only displays 2 numbers.

### Expected outcome

paper-input displays as many digits as in max

### Actual outcome

paper-input displays 2 digits always

### Steps to reproduce

1. `<paper-slider min="20" max = "230" editable="true></paper-slider>
2. move slider to 120

### Browsers Affected

- [x] Chrome

**Comment by GoceRibeski** [comment]
Same issue when the step = 0.1, as:
`<paper-slider class="red"  min="0.8" max="1.2" step="0.1" editable>`

**Comment by goatandsheep** [comment]
@GoceRibeski Unfortunately, I believe these elements are dead and will be deprecated by future elements, since Polymer 3 is (hopefully) on the cusp of a proper release. I still do have high hopes this bug will at least be fixed in the update

**Comment by keanulee** [comment]
You may be able to use `--paper-slider-input` in change the font-size or width of the embedded input.

**Comment by nextjstuts** [comment]
`/* paper-input */
    .slider-input {
      width: 50px;
`
just change the width to 70px
It's been a year and the developer has not fixed this in the demo for this component so it's never going to be fixed.
